Fix error message when "~/.metro" doesn't exist.
This fixes the following exception. It also moves it to the runtime exception instead of returning None which causes confusing exceptions later in the code:
Traceback (most recent call last):
  File "../metro", line 344, in <module>
    m.run()
  File "../metro", line 96, in run
    settings = self.setup.getSettings(self.metro_args)
  File "/var/git/metro/modules/metro_support.py", line 45, in getSettings
    print("Please copy %s to ~/.metro and customize for your environment." % (libdir+"/metro.conf"))
NameError: name 'libdir' is not defined
build failure